### ISSUE TITLE
cannot make: g++ /usr/bin/ld: cannot find -lbcm_host: No such file or directory

### ISSUE THREAD

**Issue by CRdeGraaf** [F5OEO/librpitx#20]
Hi, there is a problem installing on my system. make fails on a fresh rpi 4b running raspbian os

make inside librpitx/src fails on the line:
g++ -fPIC -shared -o librpitx.so mailbox.o raspberry_pi_revision.o rpi.o amdmasync.o atv.o dma.o dsp.o fmdmasync.o fskburst.o gpio.o iqdmasync.o ngfmdmasync.o ookburst.o phasedmasync.o serialdmasync.o util.o -lm -lrt -lpthread -L/opt/vc/lib -lbcm_host -fPIC
/usr/bin/ld: cannot find -lbcm_host: No such file or directory

I did some digging, a package was missing that is required. it is contained in libraspberrypi-dev.

I fixed it by first running apt install libraspberrypi-dev before making. it should be a required dependancy.

I propose it is mentioned somewhere or included.

Warning: this also breaks parent repo rpitx when performing install.sh.

issue can be closed.

**Comment by ghost** [comment]
> libraspberrypi-dev

What repo is this on? I am on debian bookworm and it is not included in it.

**Comment by CRdeGraaf** [comment]
> > libraspberrypi-dev
> 
> What repo is this on? I am on debian bookworm and it is not included in it.

I was on a fresh raspbian install. I (maybe wrongly) assumed that this package was specific to the rpi. Were you on a vanilla debian, or the raspbian variant? This package is included in the default, but raspberry pi specific repositories. Raspbian includes several extra pi specific repos.
